### ISSUE TITLE
Issue in creating all tikz data

### ISSUE THREAD

**Issue by abhishekpanigrahi1996** [potamides/AutomaTikZ#12]
Hi,

We are attempting to download the entire Tikz dataset for an academic project. We have downloaded all Arxiv files in JSON format. However, when we set "DATIKZ_ARXIV_FILES" to the list of all JSON files separated by ":", we get the following error.

Generating train split: 2042 examples [21:02,  1.62 examples/s]
Traceback (most recent call last):
  File "/n/fs/ptml/ap34/miniconda3/envs/tikz_env/lib/python3.11/site-packages/datasets/builder.py", line 1670, in _prepare_split_single
    for key, record in generator:
  File "/u/ap34/.cache/huggingface/modules/datasets_modules/datasets/datikz/f7ba6aed3b7ff89a640c2cebf2bcc9597f8fab334d1679346f7c83c56c37fa14/datikz.py", line 256, in _generate_examples
    for example in skip_on_error(p.imap_unordered(self._compile, loader)):
  File "/u/ap34/.cache/huggingface/modules/datasets_modules/datasets/datikz/f7ba6aed3b7ff89a640c2cebf2bcc9597f8fab334d1679346f7c83c56c37fa14/datikz.py", line 238, in skip_on_error
    yield next(loader)
          ^^^^^^^^^^^^
  File "/n/fs/ptml/ap34/miniconda3/envs/tikz_env/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
NotADirectoryError: [Errno 20] Not a directory: 'datikz/arxiv-latex-extract/extracted/arXiv_src_2009_049.jsonl'

**Comment by abhishekpanigrahi1996** [comment]
We further tried to simply set "DATIKZ_ARXIV_FILES" to the directory containing all the files and we got the following error. 

IsADirectoryError: [Errno 21] Is a directory: 'datikz/arxiv-latex-extract/extracted'

**Comment by potamides** [comment]
>However, when we set "DATIKZ_ARXIV_FILES" to the list of all JSON files separated by ":", we get the following error.

Thank you for reporting this issue! I just commited a fix which should solve it. Please try that again and let me know if you experience any other issues.

>We further tried to simply set "DATIKZ_ARXIV_FILES" to the directory containing all the files and we got the following error.

Only `jsonl` or archives containing them are supported. I have updated the README to make that more clear.
