### ISSUE TITLE
Unable to run examples/eval.py

### ISSUE THREAD

**Issue by YR22hahaha** [potamides/AutomaTikZ#18]
Thank you for publishing this wonderful project!

I got the following error when I tried to run examples/eval.py.
Options were specified as follows.
```
python eval.py --trainset train-00000-of-00002.parquet --testset test-00000-of-00001.parquet --output . --path adapter_model.bin=https://huggingface.co/nllg/tikz-clima-7b/resolve/main/adapter_model.bin
```
At first I got the following error.
```
KeyError: 'model.mm_projector.weight'
```
I modified automatikz/infer/load.py

'model.mm_projector.weight'→'base_model.model.model.mm_projector.weight'

and ran eval.py again and got the following error.
```
RuntimeError: Error(s) in loading state_dict for Linear:
	size mismatch for weight: copying a param with shape torch.Size([32000, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 1024]).
```
It is also possible that the options are specified incorrectly.
It would be helpful to know how to run eval.py.

**Comment by potamides** [comment]
Hi, thank you for your interest in our work! Could try running the command as follows (and undo your code modifications):

```bash
python eval.py --trainset train-00000-of-00002.parquet --testset test-00000-of-00001.parquet --output . --path adapter_model.bin=nllg/tikz-clima-7b
```

If you supply an URL to a specific file, the loader interprets this as a file with only the projector weights (like the one [here](https://huggingface.co/nllg/tikz-clima-7b/blob/main/projector/pytorch_model.bin)), but I assume you want to load the whole model adapter. By the way, you can set the name (here you use adapter_model.bin) to any string, this is just used to identify the model in the evaluation logs.

**Comment by YR22hahaha** [comment]
Thank you for your reply!

I followed your reply and got the following error
```
ValueError: Input length of input_ids is 1200, but `max_length` is set to 1200. This can lead to unexpected behavior. _length` or, better yet, setting `max_new_tokens`.
```
Is there any way to fix this?

**Comment by YR22hahaha** [comment]
Thank you for your reply!

I followed your reply and when I did, I got an error when about 30% of the model was loaded.
```
Traceback (most recent call last):
  File "/home/a24705/study/AutomaTikZ-WebUI/AutomaTikZ/examples/eval.py", line 209, in <module>
    tikz = generate_and_repair(generator, prompt=item['caption'], return_list=True)
  File "/home/a24705/study/AutomaTikZ-WebUI/AutomaTikZ/examples/eval.py", line 129, in generate_and_repair
    return _generate_and_repair(**kwargs)
  File "/home/a24705/study/AutomaTikZ-WebUI/AutomaTikZ/examples/eval.py", line 116, in _generate_and_repair
    new_tikz = _generate_and_repair(
  File "/home/a24705/study/AutomaTikZ-WebUI/AutomaTikZ/examples/eval.py", line 108, in _generate_and_repair
    tikz = generator(caption=prompt, snippet=_snippet, **kwargs)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/automatikz/infer/tikz.py", line 272, in __call__
    return self.generate(*args, **kwargs)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/automatikz/infer/tikz.py", line 266, in generate
    return TikzDocument(snippet + self._run_pipeline( # type: ignore
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/automatikz/infer/tikz.py", line 211, in _run_pipeline
    text = self.pipeline(prompt, **kwargs)[0]["generated_text"] # type: ignore
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 272, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1302, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1309, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1209, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 370, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2068, in generate
    self._validate_generated_length(generation_config, input_ids_length, has_default_max_length)
  File "/home/a24705/study/AutomaTikZ-WebUI/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1383, in _validate_generated_length
    raise ValueError(
ValueError: Input length of input_ids is 1200, but `max_length` is set to 1200. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.
```
The following statement is also displayed before the model begins loading. 
Is this related to an error?
```
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
```

**Comment by potamides** [comment]
>I followed your reply and when I did, I got an error when about 30% of the model was loaded.

Just to clarify, do you mean 30% of the test set was completed or really model loading? In either case, this indeed could be a bug in the testing code. But interestingly, it have never encountered it during my experiments. Which testset do you use?

Also, the line numbers for `automatikz/infer/tikz.py` in your stack trace don't match up with my version, did you make any changes?
