### ISSUE TITLE
Dataset main.py error

### ISSUE THREAD

**Issue by sanjayss34** [potamides/AutomaTikZ#6]
After installing the requirements with `pip install -r requirements.txt`, I get the following error when running `python main.py`:
```
Traceback (most recent call last):
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    response.raise_for_status()
  File "/home/sanjayss/miniconda3/envs/tikz/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/localmodels/WizardLM-13B-1.0/resolve/main/tokenizer.model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sanjayss/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1360, in hf_hub_download
    raise head_call_error
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1233, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1622, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/sanjayss/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 310, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-65449ac1-76468a232531cba45ec27d45;3069a5d7-5350-4560-8118-4819f85ed096)

Repository Not Found for url: https://huggingface.co/localmodels/WizardLM-13B-1.0/resolve/main/tokenizer.model.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sanjayss/.local/lib/python3.10/site-packages/datasets/load.py", line 1767, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/sanjayss/.local/lib/python3.10/site-packages/datasets/load.py", line 1524, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/home/sanjayss/.local/lib/python3.10/site-packages/datasets/builder.py", line 336, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/home/sanjayss/.local/lib/python3.10/site-packages/datasets/builder.py", line 490, in _create_builder_config
    builder_config = self.BUILDER_CONFIG_CLASS(**config_kwargs)
  File "/home/sanjayss/.cache/huggingface/modules/datasets_modules/datasets/datikz/f7ba6aed3b7ff89a640c2cebf2bcc9597f8fab334d1679346f7c83c56c37fa14/datikz.py", line 104, in __init__
    self.chatbot = WizardLM(bs=bs, prefix=PROMPT_PREFIX, model_max_length=512) # tight on memory
  File "/home/sanjayss/AutomaTikZ/dataset/llm/chat.py", line 89, in __init__
    super().__init__(*args, model=model, **kwargs)
  File "/home/sanjayss/AutomaTikZ/dataset/llm/chat.py", line 33, in __init__
    self.tokenizer = LlamaTokenizer.from_pretrained(model, padding_side="left", **tokenizer_kwargs),
  File "/home/sanjayss/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1800, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/sanjayss/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 433, in cached_file
    raise EnvironmentError(
OSError: localmodels/WizardLM-13B-1.0 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
```

Can you please advise on how to fix this? If you could directly provide the data (captions and TikZ code), that would be very helpful!

**Comment by potamides** [comment]
Thank you for reporting the problem, it should be fixed now. We do have a public version of DaTikZ 1.0 [here](https://github.com/potamides/AutomaTikZ/releases/tag/v1.0.0), with the caveat that we had to filter out some TikZ pictures due to licensing issues.
